const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const jwt = require("jsonwebtoken");
const config = require("config");
const _ = require("lodash");

const chartSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  chart_title: { type: String, default: '' },
  property_id: { type: String, default: '' },
  currencyValues: { type: Object },
  agent: {
    fullName: { type: String, default: '' },
    company: { type: String, default: '' },
    phone: { type: String, default: '' },
    email: { type: String, default: '' },
    website: { type: String, default: '' },
    photo: { type: String, default: '' },
    photo_50X50: { type: String, default: '' },
    photo_150X150: { type: String, default: '' },
    photo_250X250: { type: String, default: '' },
    logo: { type: String, default: '' },
    logo_50X50: { type: String, default: '' },
    logo_150X150: { type: String, default: '' },
    logo_250X250: { type: String, default: '' },
    streetAddress: { type: String, default: '' },
    city: { type: String, default: '' },
    zip: { type: String, default: '' }
  },
  client: {
    client_id: { type: String, default: '' },
    first: { type: String, default: '' },
    last: { type: String, default: '' },
    phone: { type: String, default: '' },
    email: { type: String, default: '' }
  },
  targetProperty: {
    address: { type: String, default: '' },
    city: { type: String, default: '' },
    state: { type: String, default: '' },
    zip: { type: String, default: '' },
    image: { type: String, default: '' },
    squareFootage: { type: String, default: '' },
    lat: { type: Number, default: 0 },
    lng: { type: Number, default: 0 },
    // Star Ratings
    site: { type: String, default: '3' },
    layout: { type: String, default: '3' },
    condition: { type: String, default: '3' },
    quality: { type: String, default: '3' },
    seasonality: { type: Date, default: Date.now },
    bedroom: { type: Number, default: 0 },
    bathroom: { type: Number, default: 0 },
    mls_number: { type: String, default: '' },
    property_type: { type: String, default: '' },
  },
  relatedProperty: {
    researchCheck: { type: Boolean, default: false },
    mls: { type: String, default: 'APC' },
    mls_id: { type: String, default: '' },
    propertySubType: { type: String, default: 'All' },
    pcborPropType: { type: String, default: 'All' },
    listing_type: { type: String, default: null },
    furnished: { type: String, default: '' },
    wf: { type: String, default: 'N/A' },
    pool: { type: String, default: 'N/A' },
    hopa: { type: String, default: 'N/A' },
    hoa: { type: String, default: 'N/A' },
    folionumber: { type: String, default: 'N/A' },
    bed: { type: String, default: 'N/A' },
    bath: { type: String, default: 'N/A' },
    subDivisionArray: [{ type: String, default: 'None' }],
    zipCodeArray: [{ type: String, default: 'None' }],
    areaArray: [{ type: String, default: 'None' }],
    minYear: { type: String, default: '' },
    maxYear: { type: String, default: '' },
    builtYear: { type: String, default: '' },
    minPrice: { type: String, default: '0' },
    maxPrice: { type: String, default: '' },
    minArea: { type: String, default: '0' },
    maxArea: { type: String, default: '' },
    minClose: { type: Date, default: Date.now },
    maxClose: { type: Date, default: Date.now },
    isSSO: { type: Boolean, default: false },
  },
  mapDetailCenter: {
    lat: { type: Number, default: 0 },
    lng: { type: Number, default: 0 },
    zoom: { type: Number, default: 0 }
  },
  marketConditions: {
    compActiveListings: { type: String, default: '' },
    compSoldListings: { type: String, default: '' },
    compPendingListings: { type: String, default: '' },
    compListingsTotal: { type: String, default: '' },
    dateRange: { type: String, default: '' }
  },
  relatedHomes: [{
    mlsNumber: { type: String, default: '' },
    address: { type: String, default: '' },
    city: { type: String, default: '' },
    state: { type: String, default: '' },
    zip: { type: String, default: '' },
    lat: { type: String, default: '' },
    long: { type: String, default: '' },
    yearBuilt: { type: String, default: '' },
    bed: { type: String, default: '-' },
    bath: { type: String, default: '-' },
    days: { type: String, default: '-' },
    daysPx: { type: String, default: '-' },
    status: { type: String, default: '' },
    squareFootage: { type: String, default: '' },
    price: { type: String, default: '' },
    closePrice: { type: String, default: '' },
    listPrice: { type: String, default: '' },
    saleDate: { type: Date, default: '' },
    priceSqFt: { type: String, default: '' },
    salesToList: { type: String, default: '' },
    photos: [{ type: String, default: '' }],
  }],
  activeHomes: [{
    mlsNumber: { type: String, default: '' },
    address: { type: String, default: '' },
    city: { type: String, default: '' },
    state: { type: String, default: '' },
    zip: { type: String, default: '' },
    lat: { type: String, default: '' },
    long: { type: String, default: '' },
    yearBuilt: { type: String, default: '' },
    bed: { type: String, default: '-' },
    bath: { type: String, default: '-' },
    days: { type: String, default: '-' },
    daysPx: { type: String, default: '-' },
    status: { type: String, default: '' },
    squareFootage: { type: String, default: '' },
    price: { type: String, default: '' },
    closePrice: { type: String, default: '' },
    listPrice: { type: String, default: '' },
    saleDate: { type: Date, default: '' },
    priceSqFt: { type: String, default: '' },
    salesToList: { type: String, default: '' },
    photos: [{ type: String, default: '' }],
  }],
  pendingHomes: [{
    mlsNumber: { type: String, default: '' },
    address: { type: String, default: '' },
    city: { type: String, default: '' },
    state: { type: String, default: '' },
    zip: { type: String, default: '' },
    lat: { type: String, default: '' },
    long: { type: String, default: '' },
    yearBuilt: { type: String, default: '' },
    bed: { type: String, default: '-' },
    bath: { type: String, default: '-' },
    days: { type: String, default: '-' },
    daysPx: { type: String, default: '-' },
    status: { type: String, default: '' },
    squareFootage: { type: String, default: '' },
    price: { type: String, default: '' },
    closePrice: { type: String, default: '' },
    listPrice: { type: String, default: '' },
    saleDate: { type: Date, default: '' },
    priceSqFt: { type: String, default: '' },
    salesToList: { type: String, default: '' },
    photos: [{ type: String, default: '' }],
  }],
  closedHomes: [{
    mlsNumber: { type: String, default: '' },
    address: { type: String, default: '' },
    city: { type: String, default: '' },
    state: { type: String, default: '' },
    zip: { type: String, default: '' },
    lat: { type: String, default: '' },
    long: { type: String, default: '' },
    yearBuilt: { type: String, default: '' },
    bed: { type: String, default: '-' },
    bath: { type: String, default: '-' },
    days: { type: String, default: '-' },
    daysPx: { type: String, default: '-' },
    status: { type: String, default: '' },
    squareFootage: { type: String, default: '' },
    price: { type: String, default: '' },
    closePrice: { type: String, default: '' },
    listPrice: { type: String, default: '' },
    saleDate: { type: Date, default: '' },
    priceSqFt: { type: String, default: '' },
    salesToList: { type: String, default: '' },
    photos: [{ type: String, default: '' }],
  }],
  investment: {
    LoantoValue: { type: String, trim: true, default: '' },
    advanced: { type: String, trim: true, default: '' },
    propertyValueRes_chart_id: { type: String, trim: true, default: '' },
    propertyValueRes: { type: String, trim: true, default: '' },
    propertyValueRen_chart_id: { type: String, trim: true, default: '' },
    propertyValueRental: { type: String, trim: true, default: '' },
    loanvalue: { type: String, trim: true, default: '' },
    propertyInsurance: { type: String, trim: true, default: '' },
    rtaxes: { type: String, trim: true, default: '' },
    annual_hoa: { type: String, trim: true, default: '' },
    landValue: { type: String, trim: true, default: '' },
    Improvements: { type: String, trim: true, default: '' },
    BuildingValue: { type: String, trim: true, default: '' },
    TotalImprovementValue: { type: String, trim: true, default: '' },
    RateofInflation: { type: String, trim: true, default: '' },
    HouseValueAppreciation: { type: String, trim: true, default: '' },
    CostofSale: { type: String, trim: true, default: '' },
    EstimatedVacancy: { type: String, trim: true, default: '' },
    NominalFederalIncomeTaxRate: { type: String, trim: true, default: '' },
    NominalStateIncomeTaxRate: { type: String, trim: true, default: '' },
    NominalLocalIncomeTaxRate: { type: String, trim: true, default: '' },
    NominalStraightLineRecaptureTaxRate: { type: String, trim: true, default: '' },
    NominalFederalCapitalGainTaxRate: { type: String, trim: true, default: '' },
    NominalStateCapitalGainTaxRate: { type: String, trim: true, default: '' },
    NominalLocalCapitalGainTaxRate: { type: String, trim: true, default: '' },
    FmInterestRate: { type: String, trim: true, default: '' },
    FmTerm: { type: String, trim: true, default: '' },
    SmLoantoValueorLoanAmount: { type: String, trim: true, default: '' },
    SmInterestRate: { type: String, trim: true, default: '' },
    SmTerm: { type: String, trim: true, default: '' },
    Repairs: { type: String, trim: true, default: '' },
    RegimeFee: { type: String, trim: true, default: '' },
    Electric: { type: String, trim: true, default: '' },
    Water: { type: String, trim: true, default: '' },
    Accounting: { type: String, trim: true, default: '' },
    Liscenses: { type: String, trim: true, default: '' },
    Advertising: { type: String, trim: true, default: '' },
    Trash: { type: String, trim: true, default: '' },
    monitoring: { type: String, trim: true, default: '' },
    maintenance: { type: String, trim: true, default: '' },
    Pest: { type: String, trim: true, default: '' },
    Management: { type: String, trim: true, default: '' },
    Other: { type: String, trim: true, default: '' },
    EstimatedClosingCosts: { type: String, trim: true, default: '' },
    DownpaymentorEquity: { type: String, trim: true, default: '' },
    LoantoValueSm: { type: String, trim: true, default: '' },
    FmEstimatedClosingCosts: { type: String, trim: true, default: '' },
    //Smloanvalue: {type: String,trim: true, default: ''},
    SmEstimatedClosingCosts: { type: String, trim: true, default: '' },
  },
  offMarketHomes: [{
    mlsNumber: { type: String, default: '' },
    address: { type: String, default: '' },
    city: { type: String, default: '' },
    state: { type: String, default: '' },
    zip: { type: String, default: '' },
    lat: { type: String, default: '' },
    long: { type: String, default: '' },
    yearBuilt: { type: String, default: '' },
    bed: { type: String, default: '-' },
    bath: { type: String, default: '-' },
    days: { type: String, default: '-' },
    daysPx: { type: String, default: '-' },
    status: { type: String, default: '' },
    squareFootage: { type: String, default: '' },
    price: { type: String, default: '' },
    closePrice: { type: String, default: '' },
    listPrice: { type: String, default: '' },
    saleDate: { type: Date, default: '' },
    priceSqFt: { type: String, default: '' },
    salesToList: { type: String, default: '' },
    photos: [{ type: String, default: '' }],
  }],
  created: { type: Date, default: Date.now },
  updated: { type: Date, default: Date.now }
});

const Chart = mongoose.model("Chart", chartSchema);

exports.Chart = Chart;