FROM node:12-alpine


WORKDIR /home/node/app/

#COPY package*.json ./

COPY . .
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp \
    && mkdir uploads

EXPOSE 8080
ENTRYPOINT node app.js	
